=== feiqing/Matrix/matrix-extension/src/main/resources/matrix/extension.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns="https://www.alibaba.com/matrix/extension"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="https://www.alibaba.com/matrix/extension"
            elementFormDefault="qualified">

    <xsd:element name="Extensions">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Extension" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Extension">
        <xsd:annotation>
            <xsd:documentation>Extension Definition</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="ExtensionBase" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="ExtensionImpl" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attributeGroup ref="extensionAttrs"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:attributeGroup name="extensionAttrs">
        <xsd:attribute name="class" type="xsd:string" use="required">
            <xsd:annotation>
                <xsd:documentation>Extension Class Name</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="desc" type="xsd:string" use="optional">
            <xsd:annotation>
                <xsd:documentation>Extension Description</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:attributeGroup>

    <xsd:element name="ExtensionBase">
        <xsd:annotation>
            <xsd:documentation>Extension Default Implementation(REQUIRED): When no specific implementation is found, the
                default implementation is automatically used
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:choice>
                <xsd:element ref="object"/>
                <xsd:element ref="bean"/>
                <xsd:element ref="guice"/>
                <xsd:element ref="provider"/>
            </xsd:choice>
            <xsd:attributeGroup ref="extensionBaseAttrs"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:attributeGroup name="extensionBaseAttrs">
        <xsd:attribute name="type" type="BaseType" use="required">
            <xsd:annotation>
                <xsd:documentation>ExtensionBase Implementation Type(Like: spring bean、dubbo、groovy)</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:attributeGroup>

    <xsd:simpleType name="BaseType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="object"/>
            <xsd:enumeration value="bean"/>
            <xsd:enumeration value="guice"/>
            <xsd:enumeration value="provider"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="ExtensionImpl">
        <xsd:annotation>
            <xsd:documentation>Extension Implementation Definition</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:choice>
                <xsd:element ref="object"/>
                <xsd:element ref="bean"/>
                <xsd:element ref="guice"/>
                <xsd:element ref="hsf"/>
                <xsd:element ref="dubbo"/>
                <xsd:element ref="http"/>
                <xsd:element ref="groovy"/>
                <xsd:element ref="spel"/>
                <xsd:element ref="provider"/>
            </xsd:choice>
            <xsd:attributeGroup ref="extensionImplAttrs"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:attributeGroup name="extensionImplAttrs">
        <xsd:attribute name="namespace" type="xsd:string" use="optional" default="BASE">
            <xsd:annotation>
                <xsd:documentation>Extension Domain Definition: Support multi definition by ',' separator
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="code" type="xsd:string" use="required">
            <xsd:annotation>
                <xsd:documentation>Extension Identity Definition: Support multi definition by ',' separator
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="type" type="ImplType" use="required">
            <xsd:annotation>
                <xsd:documentation>ExtensionImpl Implementation Type(Like: spring bean、dubbo、groovy)</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="priority" type="xsd:long" default="0">
            <xsd:annotation>
                <xsd:documentation>Extension Priority Definition: The Smaller The Priority The Higher Priority
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="lazy" type="xsd:boolean" default="false">
            <xsd:annotation>
                <xsd:documentation>Enable Lazy Loading: Runtime Loads The Implementation</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="desc" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation>Extension Implementation Description</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:attributeGroup>

    <xsd:simpleType name="ImplType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="object"/>
            <xsd:enumeration value="bean"/>
            <xsd:enumeration value="guice"/>

            <xsd:enumeration value="hsf"/>
            <xsd:enumeration value="dubbo"/>
            <xsd:enumeration value="http"/>

            <xsd:enumeration value="groovy"/>
            <xsd:enumeration value="spel"/>
            <xsd:enumeration value="provider"/>

            <xsd:enumeration value="sql(*NOT-SUPPORT*)"/>

            <xsd:enumeration value="ognl(*NOT-SUPPORT*)"/>
            <xsd:enumeration value="mvel(*NOT-SUPPORT*)"/>

            <xsd:enumeration value="lua(*NOT-SUPPORT*)"/>
            <xsd:enumeration value="python(*NOT-SUPPORT*)"/>
            <xsd:enumeration value="javascript(*NOT-SUPPORT*)"/>

            <xsd:enumeration value="rocketmq(*NOT-SUPPORT*)"/>
            <xsd:enumeration value="kafka(*NOT-SUPPORT*)"/>

            <!--            <xsd:enumeration value="calcite(*NOT-SUPPORT*)"/>-->
            <!--            <xsd:enumeration value="cassandra(*NOT-SUPPORT*)"/>-->
            <!--            <xsd:enumeration value="presto(*NOT-SUPPORT*)"/>-->
            <!--            <xsd:enumeration value="clickhouse(*NOT-SUPPORT*)"/>-->
            <!--            <xsd:enumeration value="elasticsearch(*NOT-SUPPORT*)"/>-->
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="object">
        <xsd:annotation>
            <xsd:documentation>Custom Object Type Extension Implementation</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="class" type="xsd:string" use="required">
                <xsd:annotation>
                    <xsd:documentation>class</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="arg0" type="xsd:string" use="optional">
                <xsd:annotation>
                    <xsd:documentation>The First Parameter(Currently Only One Parameter Can Be Added)
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="bean">
        <xsd:annotation>
            <xsd:documentation>spring bean Type Extension Implementation Definition
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="optional">
                <xsd:annotation>
                    <xsd:documentation>spring bean name</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="class" type="xsd:string" use="optional">
                <xsd:annotation>
                    <xsd:documentation>spring bean class</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="guice">
        <xsd:annotation>
            <xsd:documentation>Guice Type Extension Implementation Definition</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="class" type="xsd:string" use="required">
                <xsd:annotation>
                    <xsd:documentation>guice instance class</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="name" type="xsd:string" use="optional">
                <xsd:annotation>
                    <xsd:documentation>guice instance @Named(value = 'name')</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="hsf">
        <xsd:annotation>
            <xsd:documentation>HSF Type Extension Implementation Definition</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="service" type="xsd:string" use="required"/>
            <xsd:attribute name="version" type="xsd:string" use="required">
                <xsd:annotation>
                    <xsd:documentation>HSF Service Version Definition(REQUIRED)</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="group" type="xsd:string" default="HSF"/>
            <xsd:attribute name="timeout" type="xsd:long">
                <xsd:annotation>
                    <xsd:documentation>clientTimeOut Setting</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="dubbo">
        <xsd:annotation>
            <xsd:documentation>dubbo Type Extension Implementation Definition</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="version" type="xsd:string"/>
            <xsd:attribute name="group" type="xsd:string"/>
            <xsd:attribute name="timeout" type="xsd:long">
                <xsd:annotation>
                    <xsd:documentation>clientTimeOut Setting</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="check" type="xsd:boolean" default="true"/>
            <xsd:attribute name="filter" type="xsd:string"/>
            <xsd:attribute name="application-name" type="xsd:string"/>
            <xsd:attribute name="registry-address" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="http">
        <xsd:annotation>
            <xsd:documentation>For Demo Purposes Only
                <p color="red">Do not use in Product Environment!!!</p>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="schema" type="xsd:string"/>
            <xsd:attribute name="host" type="xsd:string"/>
            <xsd:attribute name="port" type="xsd:string" default="80"/>
            <xsd:attribute name="path" type="xsd:string"/>
            <xsd:attribute name="method" type="xsd:string" default="POST"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="groovy">
        <xsd:annotation>
            <xsd:documentation>For Demo Purposes Only
                <p color="red">Do not use in Product Environment!!!</p>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="protocol" type="xsd:string" use="required"/>
            <xsd:attribute name="path" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="spel">
        <xsd:annotation>
            <xsd:documentation>For Demo Purposes Only
                <p color="red">Do not use in Product Environment!!!</p>
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="protocol" type="xsd:string" use="required"/>
            <xsd:attribute name="path" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="provider">
        <xsd:annotation>
            <xsd:documentation>Extension implementation definitions of custom types</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="class" type="xsd:string" use="required">
                <xsd:annotation>
                    <xsd:documentation>provider class</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>

            <xsd:attribute name="method" type="xsd:string" use="required">
                <xsd:annotation>
                    <xsd:documentation>provider method class(static)</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>

            <xsd:attribute name="arg0" type="xsd:string" use="optional">
                <xsd:annotation>
                    <xsd:documentation>provider method arg0</xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== feiqing/Matrix/matrix-extension/src/test/resources/matrix-extension-demo.xml
<?xml version="1.0" encoding="utf-8"?>
<Extensions xmlns="https://www.alibaba.com/matrix/extension"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://www.alibaba.com/matrix/extension https://www.alibaba.com/matrix/extension.xsd">

    <Extension class="com.alibaba.matrix.extension.test.ext.ShowDemoExt" base="showDemoExtBaseImpl">
        <ExtensionImpl code="my-code-2" type="http" priority="1">
            <http url="http://localhost:8080/" method="POST"/>
        </ExtensionImpl>

    </Extension>

    <Extension class="java.util.function.Function" base="baseFunctionImpl" desc="测试扩展Function定义">
        <ExtensionImpl scope="BASE, XXX" code="yhb, xxx" type="bean" desc="验货宝">
            <bean class="com.alibaba.matrix.extension.test.impl.function.YhbFunctionImpl"/>
        </ExtensionImpl>
        <ExtensionImpl code="groovy" type="http">
            <http url="xxx"/>
        </ExtensionImpl>
    </Extension>

    <Extension class="java.util.function.BiFunction" base="baseBiFunctionImpl">
        <ExtensionImpl code="groovy" type="groovy">
<!--            <groovy protocol="nacos" path="serverAddr=localhost:8848;namespace=c8914181-d464-4f9b-a9d6-2a124205793a;dataId=bg-aristotle-api.force.h5.uid.gray;scope=DEFAULT_scope"/>-->
            <groovy protocol="file" path="/Users/feiqing.zjf/IdeaProjects/自己/demo/src/test/java/com/alibaba/matrix/demo/Test.groovy"/>
<!--            <groovy protocol="http" path="http://127.0.0.1:8080/test.groovy"/>-->
        </ExtensionImpl>
    </Extension>

    <Extension class="java.util.function.Supplier" base="baseSupplierImpl" desc="测试扩展Supplier定义">
        <ExtensionImpl scope="BASE" code="xxx, hhh" type="dubbo">
            <dubbo version="xxx" group="xxx" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl scope="BASE" code="xxx" type="bean" desc="">
            <bean name="xxx" class="java.util.function.Supplier" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="yhb" type="hsf" desc="验货宝">
            <hsf service="xxx" group="xxx" version="xxx.yhb" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="dubbo" type="dubbo">
            <dubbo version="sss" timeout="100" check="true" group="xxx" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="http" type="http">
            <http url="https://www.baidu.com/rest/" method="POST" camelToUnderline="true"/>
        </ExtensionImpl>
    </Extension>

    <!--
    <Extension class="com.alibaba.matrix.test.extension.spi.OrderCreateSpi" base="baseOrderCreateSpiImpl"
               desc="下单扩展能力">
        <ExtensionImpl code="normal" type="bean" desc="普通电商交易">
            <bean name="normalOrderCreateSpiImpl"/>
        </ExtensionImpl>
        <ExtensionImpl code="o2c" type="bean" desc="O2O交易">
            <bean name="o2OOrderCreateSpiImpl"/>
        </ExtensionImpl>
    </Extension>
    -->

</Extensions>

=== feiqing/Matrix/matrix-extension/src/test/resources/extension/matrix-extension-remote.xml
<?xml version="1.0" encoding="utf-8"?>
<Extensions xmlns="https://www.alibaba.com/matrix/extension"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://www.alibaba.com/matrix/extension https://www.alibaba.com/matrix/extension.xsd">

    <Extension class="com.alibaba.matrix.extension.test.ext.DemoRemoteExt" base="blankDemoRemoteExtImpl"
               desc="Demo远程扩展定义">
        <ExtensionImpl code="code.http.post" type="http">
            <http schema="http" host="localhost" port="8080" path="/remote_service/" method="POST" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.http.get" type="http">
            <http schema="http" host="localhost" port="8080" path="/remote_service/" method="GET" lazy="true"/>
        </ExtensionImpl>

        <ExtensionImpl code="code.http" type="http">
            <http schema="http" host="localhost" port="8080" path="/remote_service/" method="GET" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.http" type="http">
            <http schema="http" host="localhost" port="8080" path="/remote_service/" method="GET" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.http" type="http">
            <http schema="http" host="localhost" port="8080" path="/remote_service/" method="GET" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.http" type="http">
            <http schema="http" host="localhost" port="8080" path="/remote_service/" method="GET" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.http" type="http">
            <http schema="http" host="localhost" port="8080" path="/remote_service/" method="GET" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.http" type="http">
            <http schema="http" host="localhost" port="8080" path="/remote_service/" method="GET" lazy="true"/>
        </ExtensionImpl>
    </Extension>

</Extensions>

=== feiqing/Matrix/matrix-extension/src/test/resources/extension/matrix-extension-test.xml
<?xml version="1.0" encoding="utf-8"?>
<Extensions xmlns="https://www.alibaba.com/matrix/extension"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://www.alibaba.com/matrix/extension https://www.alibaba.com/matrix/extension.xsd">

    <Extension class="org.apache.commons.collections4.Bag" base="hashBag" desc="Object Bag定义">
        <ExtensionImpl code="code.tree" type="object">
            <object class="org.apache.commons.collections4.bag.TreeBag"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.hash" type="object">
            <object class="org.apache.commons.collections4.bag.HashBag" args="[1,2,3]" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.hash2" type="object">
            <object class="com.alibaba.matrix.extension.test.impl.base.HashBag" args="[1,2,3]"/>
        </ExtensionImpl>
    </Extension>
</Extensions>

=== feiqing/Matrix/matrix-extension/src/test/resources/extension/matrix-extension-base.xml
<?xml version="1.0" encoding="utf-8"?>
<Extensions xmlns="https://www.alibaba.com/matrix/extension"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://www.alibaba.com/matrix/extension
            https://www.alibaba.com/matrix/extension.xsd">

    <Extension class="org.apache.commons.lang3.function.TriFunction" desc="测试扩展TriFunction定义">
        <ExtensionBase type="bean">
            <bean name="baseTriFunctionImpl"/>
        </ExtensionBase>
        <ExtensionImpl code="code.object" type="object">
            <object class="com.alibaba.matrix.extension.test.impl.function.ObjectTriFunctionExtImpl" arg0="OBJ-TEST"/>
        </ExtensionImpl>

        <ExtensionImpl code="code.common" type="bean">
            <bean class="com.alibaba.matrix.extension.test.impl.function.CommonTriFunctionExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.yhb" type="bean">
            <bean class="com.alibaba.matrix.extension.test.impl.function.YhbTriFunctionExtImpl"/>
        </ExtensionImpl>

        <ExtensionImpl code="code.sub.scope" type="bean">
            <bean class="com.alibaba.matrix.extension.test.impl.function.SubScopeTriFunctionExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.sub.scope" type="bean">
            <bean class="com.alibaba.matrix.extension.test.impl.function.SubScopeTriFunctionExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl scope="SUB-SCOPE" code="code.sub.scope" type="bean">
            <bean class="com.alibaba.matrix.extension.test.impl.function.SubScopeTriFunctionExtImpl"/>
        </ExtensionImpl>


        <ExtensionImpl code="code.normal.concurrent" type="bean">
            <bean class="com.alibaba.matrix.extension.test.impl.function.NormalTriFunctionExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.normal.concurrent" type="bean">
            <bean class="com.alibaba.matrix.extension.test.impl.function.NormalTriFunctionExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.normal.concurrent" type="bean">
            <bean class="com.alibaba.matrix.extension.test.impl.function.NormalTriFunctionExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.normal.concurrent" type="bean">
            <bean class="com.alibaba.matrix.extension.test.impl.function.NormalTriFunctionExtImpl"/>
        </ExtensionImpl>

    </Extension>

    <Extension class="com.alibaba.matrix.extension.test.ext.DemoBaseExt" desc="测试扩展DemoBaseExt定义">
<!--        <ExtensionBase type="object">-->
<!--            <object class="com.alibaba.matrix.extension.test.impl.base.BaseDemoBaseExtImpl"/>-->
<!--        </ExtensionBase>-->
        <ExtensionBase type="guice">
            <guice class="com.alibaba.matrix.extension.test.impl.base.BaseDemoBaseExtImpl"/>
        </ExtensionBase>
        <ExtensionImpl code="code.yhb" type="bean" priority="1">
            <bean name="yhbDemoBaseExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl scope="SUB-SCOPE" code="code.yhb" type="bean">
            <bean name="yhbDemoBaseExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.common" type="bean">
            <bean name="commonDemoBaseExtImpl"/>
        </ExtensionImpl>
    </Extension>

</Extensions>

=== feiqing/Matrix/matrix-extension/src/test/resources/extension/matrix-extension-plus.xml
<?xml version="1.0" encoding="utf-8"?>
<Extensions xmlns="https://www.alibaba.com/matrix/extension"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://www.alibaba.com/matrix/extension
            https://www.alibaba.com/matrix/extension.xsd">

    <Extension class="java.util.function.Consumer" desc="测试扩展Consumer定义">
        <ExtensionBase type="bean">
            <bean name="baseConsumerImpl"/>
        </ExtensionBase>
    </Extension>

    <Extension class="java.util.function.Function" desc="测试扩展Function定义">
        <ExtensionBase type="bean">
            <bean name="baseFunctionExtImpl"/>
        </ExtensionBase>
        <ExtensionImpl priority="1" namespace="BASE, SUB-SCOPE" code="normal" type="bean" desc="普通电商交易">
            <bean name="normalFunctionExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl priority="2" code="normal" type="bean" desc="普通电商交易">
            <bean class="com.alibaba.matrix.extension.test.impl.function.NormalPriority2FunctionExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl namespace="BASE, SUB-SCOPE" code="yhb" type="bean" desc="验货宝交易">
            <bean class="com.alibaba.matrix.extension.test.impl.function.YhbFunctionExtImpl"/>
        </ExtensionImpl>
    </Extension>

    <Extension class="java.util.function.Supplier" desc="测试扩展Supplier定义">
        <ExtensionBase type="bean">
            <bean name="baseSupplierExtImpl"/>
        </ExtensionBase>
        <ExtensionImpl code="normal" type="bean" desc="普通电商交易">
            <bean name="normalSupplierExtImpl"/>
        </ExtensionImpl>
        <ExtensionImpl namespace="SUB-SCOPE" code="yhb" type="bean" desc="验货宝交易">
            <bean class="com.alibaba.matrix.extension.test.impl.function.YhbSupplierExtImpl"/>
        </ExtensionImpl>
    </Extension>

    <Extension class="java.util.function.BiConsumer" desc="测试扩展BiConsumer定义">
        <ExtensionBase type="bean">
            <bean name="baseBiConsumerImpl"/>
        </ExtensionBase>
    </Extension>

    <Extension class="java.util.function.BiFunction" desc="测试扩展BiFunction定义">
        <ExtensionBase type="bean">
            <bean name="baseBiFunctionImpl"/>
        </ExtensionBase>
    </Extension>

</Extensions>

=== feiqing/Matrix/matrix-extension/src/test/resources/extension/matrix-extension-script.xml
<?xml version="1.0" encoding="utf-8"?>
<Extensions xmlns="https://www.alibaba.com/matrix/extension"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://www.alibaba.com/matrix/extension https://www.alibaba.com/matrix/extension.xsd">

    <!-- 脚本扩展(SpEL、Groovy)-->
    <Extension class="com.alibaba.matrix.extension.test.ext.DemoScriptExt" desc="Demo脚本扩展定义">
        <ExtensionBase type="bean">
            <bean name="blankDemoScriptExtImpl"/>
        </ExtensionBase>
        <ExtensionImpl code="code.spel.nacos" type="spel" desc="SpEL扩展实现: from Nacos">
            <spel protocol="nacos"
                  path="serverAddr=localhost:8848;dataId=com.alibaba.matrix.extension.test.ext.demo.script.ext;group=DEFAULT_GROUP"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.groovy.file" type="groovy" desc="Groovy扩展实现: from File">
            <groovy protocol="file"
                    path="classpath:com.alibaba.matrix.extension.test.ext.demo.script.ext.groovy"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.groovy.nacos" type="groovy" desc="Groovy扩展实现: from Nacos">
            <groovy protocol="nacos"
                    path="serverAddr=localhost:8848;dataId=com.alibaba.matrix.extension.test.ext.demo.script.ext.groovy;group=DEFAULT_GROUP"/>
        </ExtensionImpl>
        <ExtensionImpl code="code.groovy.http" type="groovy" lazy="true" desc="Groovy扩展实现: from Http">
            <groovy protocol="http"
                    path="http://localhost:8080/com.alibaba.matrix.extension.test.ext.demo.script.ext.groovy"/>
        </ExtensionImpl>
    </Extension>

</Extensions>

=== feiqing/Matrix/src/test/resources/matrix-extension-create.xml
<?xml version="1.0" encoding="utf-8"?>
<Extensions xmlns="https://www.alibaba.com/matrix/extension"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://www.alibaba.com/matrix/extension https://www.alibaba.com/matrix/extension.xsd">

    <Extension class="java.util.function.Function" base="baseFunctionImpl" desc="测试扩展Function定义">
        <ExtensionImpl group="BASE, XXX" code="yhb, xxx" type="bean" desc="验货宝">
            <!--            <bean name="yhbFunctionImpl"/>-->
            <bean class="com.alibaba.matrix.test.extension.impl.function.YhbFunctionImpl"/>
        </ExtensionImpl>
    </Extension>

    <Extension class="java.util.function.Supplier" base="baseSupplierImpl" desc="测试扩展Supplier定义">
        <ExtensionImpl group="BASE" code="xxx, hhh" type="dubbo">
            <dubbo version="xxx" group="xxx" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl group="BASE" code="xxx" type="bean" desc="">
            <bean name="xxx" class="java.util.function.Supplier" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="yhb" type="hsf" desc="验货宝">
            <hsf service="xxx" group="xxx" version="xxx.yhb" lazy="true"/>
        </ExtensionImpl>
        <ExtensionImpl code="dubbo" type="dubbo">
            <dubbo version="sss" timeout="100" check="true" group="xxx" lazy="true"/>
        </ExtensionImpl>
    </Extension>

    <!--
    <Extension class="com.alibaba.matrix.test.extension.spi.OrderCreateSpi" base="baseOrderCreateSpiImpl"
               desc="下单扩展能力">
        <ExtensionImpl code="normal" type="bean" desc="普通电商交易">
            <bean name="normalOrderCreateSpiImpl"/>
        </ExtensionImpl>
        <ExtensionImpl code="o2c" type="bean" desc="O2O交易">
            <bean name="o2OOrderCreateSpiImpl"/>
        </ExtensionImpl>
    </Extension>
    -->

</Extensions>
